### ISSUE TITLE
any plans to add debugging via gdb

### ISSUE THREAD

**Issue by SingingBush** [thiagoabreu/vala-code#4]
would need to add something like this to the _contributes_ section of `package.json` and some code to sit between GDB and the vscode API. 

https://code.visualstudio.com/docs/extensions/example-debuggers

```json
"debuggers": [{
    "type": "gdb",
    "label": "GDB",
    "windows": {
        "program": "C:\\MinGw\\bin\\gdb.exe"
    },
    "osx": {
        "runtime": "gdb"
    },
    "linux": {
        "runtime": "gdb"
    }
}]
```

I realise it's probably a big job but it's certainly doable. The D plugin makes use of gdb so it may be possible to reuse some of its code:
https://github.com/WebFreak001/code-debug/blob/master/src/gdb.ts

**Comment by dlech** [comment]
Since vala compiles to C first, you can use the existing vscode debugger configurations for C. Just install the C/C++ extension. It just works. I've used it successfully already. I have the vala compiler save the C code files and set the directory where they are as the current working directory so that gdb can find them. And be sure to set the `-g` compile flag so that the vala line numbers are added in the C code.

**Comment by dlech** [comment]
Oh, and I have a PR that has not been merged yet that allows you to set line breaks in vala source files.

**Comment by thiagojedi** [comment]
Debugging is not the focus of this extension as the C/C++ and the [Native Debugger extension](https://marketplace.visualstudio.com/items?itemName=webfreak.debug) are already working fine. Let's not reinvent the wheel.

As @dlech explained, you'll need to compile with the right flags. There's a page with a [sample](https://github.com/thiagoabreu/vala-code/wiki/Get-Started) in the Wiki.

**Comment by SingingBush** [comment]
cheers guys, I'll check the wiki page and give it a go
